version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.4
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-autoconfigure
    versions:
    - 2.4.2
    - 2.4.4
  - dependency-name: com.google.cloud:google-cloud-storage
    versions:
    - 1.113.14
  - dependency-name: com.google.apis:google-api-services-youtube
    versions:
    - v3-rev20210407-1.31.0
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.2
  - dependency-name: org.springframework.security:spring-security-web
    versions:
    - 5.4.5
  - dependency-name: org.litote.kmongo:kmongo
    versions:
    - 4.2.3
    - 4.2.4
    - 4.2.5
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21
    - 1.4.31
    - 1.4.32
  - dependency-name: org.eclipse.jetty.http2:http2-http-client-transport
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty.http2:http2-hpack
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty.http2:http2-common
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty.http2:http2-client
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-io
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-http
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-client
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-alpn-java-client
    versions:
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-alpn-client
    versions:
    - 11.0.1
  - dependency-name: org.springframework.boot:spring-boot-starter-tomcat
    versions:
    - 2.4.3
  - dependency-name: org.jetbrains.kotlin.plugin.spring
    versions:
    - 1.4.31
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-websocket
    versions:
    - 10.0.2
  - dependency-name: org.springframework.security:spring-security-test
    versions:
    - 5.4.2
    - 5.4.4
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
  - dependency-name: io.sentry:sentry-logback
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: org.springframework.boot:spring-boot-starter-hateoas
    versions:
    - 2.4.2
  - dependency-name: org.springframework.boot:spring-boot-starter-security
    versions:
    - 2.4.2
