---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
      - name: video-service
        image: eu.gcr.io/boclips-prod/boclips/video-service:${VERSION}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        envFrom:
        - secretRef:
            name: video-service
