---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions: [{key: priority, operator: In, values: [noncritical]}]

      $TOLERATE_NONCRITICAL_STAGING

      containers:
      - name: video-service
        image: eu.gcr.io/boclips-prod/boclips/video-service:${VERSION}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
        - secretRef:
            name: video-service
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "2Gi"

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 2
          initialDelaySeconds: 40
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
