---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-service
  labels:
    app: asset-service
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: asset-service
  template:
    metadata:
      labels:
        app: asset-service
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions: [{key: priority, operator: In, values: [noncritical]}]

      $TOLERATE_NONCRITICAL_EXCEPT_PRODUCTION

      containers:
      - name: asset-service
        image: eu.gcr.io/boclips-prod/boclips/asset-service:${VERSION}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
        - secretRef:
            name: asset-service
        resources:
          requests:
            cpu: "1000m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
