---
apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: video-service
