#!/usr/bin/env bash

set -ex

./gradlew video-service:buildClient video-service:sourcesJarClient

mvn install:install-file -Dfile=./video-service/build/libs/video-service-client-0.0.1-SNAPSHOT.jar -DgroupId=${GROUP} -DartifactId=${ARTIFACT} -Dversion=${VERSION} -Dpackaging=jar