#!/usr/bin/env bash

# This assumes you have provisioned the machine
ktlint --apply-to-idea-project

# Generate YouTube contract test configuration
pushd video-service/src/test_youtube_contract/resources/
./setup-contract-test
echo "setting up YouTube contract tests"
popd

# Generate SignedLinkProvider contract tests
pushd video-service/src/test/resources/
./setup-contract-tests
echo "setting up SignedLinkProvider contract tests"
popd