kaltura:
  session:
  host:

spring:
  datasource:
    url:
    username:
    password:
  main:
    web-application-type: none

legacy-search:
  base-url:
  token:

logging:
  level:
    ROOT: warn
    com.boclips: info
