spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  flyway:
    baselineOnMigrate: true

logging:
  level:
    com.boclips.kalturaclient: debug

management:
  health:
    solr:
      enabled: false