spring:
  http:
    encoding:
      charset: UTF-8
      force: true

logging:
  config: "classpath:logback.xml"
  level:
    com.boclips.kalturaclient: info
    feign: info

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    solr:
      enabled: false
    elasticsearch:
      enabled: false
    mongo:
      enabled: false

gcs:
  secret:
  project-id:
  bucket-name:

legacy:
  solr:
    host: solr
    port: 80

server:
  use-forward-headers: true

pubsub:
  video-searchability-update:
    batch-size:
      1000

user-service:
  base-url:

batch-processing:
  video-batch-size: 1000

reindex:
  batch-size: 2000
