spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.boclips.kalturaclient: debug

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    solr:
      enabled: false

legacy:
  solr:
    host: solr
    port: 80