---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boclipsconcourse/docker-java
    tag: '0.3.0'

inputs:
  - name: source

caches:
  - path: .gradle/

run:
  path: source/search-service/pipeline/scripts/asroot.sh
