---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 'latest'

inputs:
  - name: source

caches:
  - path: .gradle/

run:
  path: source/search-service/pipeline/scripts/asroot.sh
