---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: boclipsconcourse/jdk-with-elasticsearch
    tag: 0.3.0

inputs:
  - name: source

caches:
  - path: .gradle/
  - path: source/dependency-check-cache

run:
  path: source/search-service/pipeline/scripts/test.sh

