---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 11.0.2-jdk-stretch

inputs:
  - name: source

caches:
  - path: .gradle/
  - path: source/dependency-check-cache

run:
  path: source/search-service/pipeline/scripts/asroot.sh
