#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"

api_key="$(bo show credential concourse-main boclips.videos youtube-contract-test-api-key)"
echo "YOUTUBE_API_KEY: $api_key" > "$cwd/contract-test-setup.yml"
