#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"

api_key="$(decoded-secret boclips.videos concourse-main | jq -r '.["youtube-contract-test-api-key"]')"
echo "YOUTUBE_API_KEY: $api_key" > "$cwd/contract-test-setup.yml"
