---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 8-jdk-stretch

inputs:
- name: source
- name: version

outputs:
- name: dist

params:
  YOUTUBE_API_KEY:
  GCS_SECRET:
  GCS_BUCKET_NAME:
  GCS_CONTRACT_SECRET:
  GCS_CONTRACT_BUCKET_NAME:
  GCS_PROJECT_ID:

caches:
- path: .gradle/
run:
  path: source/video-service/pipeline/scripts/build.sh
