---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 'latest'

inputs:
  - name: source
  - name: version

outputs:
  - name: dist

params:
  YOUTUBE_API_KEY:

caches:
  - path: .gradle/
  - path: source/dependency-check-cache

run:
  path: source/video-service/pipeline/scripts/build.sh
