---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-stretch

inputs:
- name: source
- name: version

outputs:
- name: dist

params:
  YOUTUBE_API_KEY:

caches:
- path: .gradle/

run:
  path: source/video-service/pipeline/scripts/build.sh
