apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: _
  labels:
    app: video-service-job
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: video-service-job
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 7200
      template:
        metadata:
          labels:
            app: video-service-job
        spec:
          restartPolicy: Never
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - operator: In
                    values:
                    - noncritical
                    key: priority
          tolerations:
          - effect: NoSchedule
            operator: Equal
            value: noncritical
            key: priority
