apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
  labels:
    app: video-service
spec:
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: video-service
        image: app:1
        env:
        - name: SENTRY_RELEASE
          value: video-service-$(VERSION)
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: video-service
