apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- reindex-collections-cronjob.yaml
- reindex-videos-cronjob.yaml
- reindex-legacy-cronjob.yaml
commonAnnotations:
  boclips-version: "194"
images:
- name: app
  newName: eu.gcr.io/boclips-prod/boclips/video-service
  newTag: "194"
patches:
- path: spread-across-zones.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: boot-time.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: scale.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: cronjob-shared.yaml
  target:
    group: batch
    kind: CronJob
    version: v1beta1
vars:
- fieldref:
    fieldPath: metadata.annotations.boclips-version
  name: VERSION
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: video-service
