---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reindex-collections
spec:
  schedule: 0 10 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reindex-collections
            image: app:0
            command:
            - java
            - -jar
            - app.jar
            envFrom:
            - secretRef:
                name: video-service
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: no-event-bus
            - name: MODE
              value: reindex-collections
            resources:
              requests:
                cpu: 1
                memory: 2G
              limits:
                cpu: 1
                memory: 2G
