apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  selector:
    app: video-service
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
