apiVersion: apps/v1
kind: Deployment
metadata:
  name: UNUSED
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: video-service
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
