apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
namespace: staging
replicas:
- count: 2
  name: video-service
patches:
- path: jaeger-service-name.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: noncritical.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: jvm-debugging.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: keycloak-configuration.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
