apiVersion: apps/v1
kind: Deployment
metadata:
  name: UNUSED
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - operator: In
                values:
                - noncritical
                key: priority
      tolerations:
      - effect: NoSchedule
        operator: Equal
        value: noncritical
        key: priority
